version: "3.7"
services:
  app:
    container_name: transparencia-app
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    volumes:
      - ./src:/var/www
    networks:
      - transparencia-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
      - app
      - nginx
    networks:
      - transparencia-network

  db:
    container_name: transparencia-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: transparencia
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
      - transparencia-network    

  nginx:
    image: nginx:alpine
    ports:
      - 8005:80
    depends_on:
      - db
      - app
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - transparencia-network

networks:
  transparencia-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
